# Generated by Django 4.2.7 on 2024-01-30 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=211)),
                ("image", models.ImageField(upload_to="category/")),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=221)),
                ("image", models.ImageField(upload_to="course/")),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("sotib_olingan", "sotib_olingan"), ("sotib_olinmagan", "sotib_olinmagan")],
                        max_length=21,
                        null=True,
                    ),
                ),
                ("price", models.FloatField(max_length=100)),
                ("discount", models.FloatField(blank=True, max_length=221, null=True)),
                ("rating", models.FloatField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="course.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interviews",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=221)),
                ("image", models.ImageField(upload_to="interviews/")),
                ("read_hour", models.IntegerField()),
                ("read_min", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SocialApps",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("instagram_url", models.CharField(max_length=221)),
                ("tik_tok_url", models.CharField(max_length=221)),
                ("you_tube_url", models.CharField(max_length=221)),
                ("telegram_url", models.CharField(max_length=221)),
                ("facebook_url", models.CharField(max_length=221)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=221)),
            ],
        ),
        migrations.CreateModel(
            name="CourseVideos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=221)),
                ("read_hour", models.IntegerField(blank=True, null=True)),
                ("read_min", models.IntegerField(blank=True, null=True)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="course.course")),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="tag",
            field=models.ManyToManyField(to="course.tag"),
        ),
    ]
