# Generated by Django 4.2.7 on 2024-01-31 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_alter_course_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursevideos",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="videos", to="course.course"
            ),
        ),
    ]
