# Generated by Django 4.2.7 on 2024-01-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0005_coursevideos_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursevideos",
            name="video",
            field=models.FileField(upload_to="course-videos/"),
        ),
    ]
