# Generated by Django 4.2.7 on 2024-01-31 15:03

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0006_alter_coursevideos_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursevideos",
            name="course",
        ),
        migrations.DeleteModel(
            name="Interviews",
        ),
        migrations.DeleteModel(
            name="SocialApps",
        ),
        migrations.RemoveField(
            model_name="course",
            name="category",
        ),
        migrations.RemoveField(
            model_name="course",
            name="content",
        ),
        migrations.RemoveField(
            model_name="course",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="course",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="course",
            name="status",
        ),
        migrations.RemoveField(
            model_name="course",
            name="tag",
        ),
        migrations.AddField(
            model_name="course",
            name="buy_user",
            field=models.ManyToManyField(blank=True, related_name="buy_course", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="price_discount",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=211),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="CourseVideos",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
