# Generated by Django 4.2.7 on 2024-01-30 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=221)),
                ("author", models.CharField(max_length=221)),
                ("image", models.ImageField(upload_to="blog/")),
                ("content", models.TextField()),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="course.category")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
